import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { ListDate } from "../components/step/listDate";
import { ListTitle } from "../components/step/listTitle";

const Create: NextPage = () => {
  const [stepNr, setStepNr] = useState<number>(1);
  return (
    <>
      <Head>
        <title>Skapa din lista</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen flex-col items-center justify-center bg-[#101827]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="translate-x-52">
            {stepNr === 1 && <ListTitle onClick={() => setStepNr(2)} />}
            {stepNr === 2 && (
              <ListDate onClick={() => console.log("Nästa steg")} />
            )}
          </div>
        </div>
      </div>
    </>
  );
};

export default Create;
