import styled from "@emotion/styled";
import { type NextPage } from "next";
import Head from "next/head";
import { mountStoreDevtool } from "simple-zustand-devtools";
import tw from "twin.macro";
import create from "zustand";
import { ListDate } from "../components/step/listDate";
import { ListTitle } from "../components/step/listTitle";

const StepCounter = styled.div<{ $step: number }>`
  ${tw`bg-gradient-to-br from-pink-500 to-orange-400 h-full rounded-tl-md duration-700 ease-out`}
  ${({ $step }) => {
    switch ($step) {
      case 1:
        return tw`w-1/3`;
      case 2:
        return tw`w-1/2`;
      case 3:
        return tw`w-full rounded-tr-md`;
    }
  }}
`;

type State = {
  currentStep: number;
};

type Actions = {
  setNextStep: () => void;
  setPrevStep: () => void;
};

export const useCreateListStore = create<State & Actions>()((set) => ({
  currentStep: 1,
  setNextStep: () => set((state) => ({ currentStep: state.currentStep + 1 })),
  setPrevStep: () => set((state) => ({ currentStep: state.currentStep - 1 })),
}));

if (process.env.NODE_ENV === "development") {
  mountStoreDevtool("Store", useCreateListStore);
}

const Create: NextPage = () => {
  const currentStep = useCreateListStore((state) => state.currentStep);
  const setNextStep = useCreateListStore((state) => state.setNextStep);

  const renderStep = () => {
    switch (currentStep) {
      case 1:
        return <ListTitle onClick={() => setNextStep()} />;
      case 2:
        return <ListDate onClick={() => console.log("Nästa steg")} />;
      default:
        break;
    }
  };

  return (
    <>
      <Head>
        <title>Skapa din lista</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col items-center bg-gray-900">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="rounded-md bg-gray-800 shadow-md lg:w-[50%]">
            <div className="h-2 w-full rounded-tl-md rounded-tr-md bg-white">
              <StepCounter $step={currentStep} />
            </div>
            {renderStep()}
          </div>
        </div>
      </div>
    </>
  );
};

export default Create;
